
import os

import exoechopy as eep

from pathlib import Path


def run():
    print("""
    Star system data can be stored using a JSON file format.  The file suffix .exo identifies template files.
    To get a template to work from, run create_system_template in io, which can also accept command line input.
    """)

    working_folder = Path.cwd()
    demo_template_filename = "demo_system_template.exo"
    eep.io.create_system_template(folder=working_folder, filename=demo_template_filename)

    star_system = eep.io.generate_system_from_file(working_folder/demo_template_filename)

    print("""
    The get_system_objects() method will provide a list of stars, planets, and telescopes generated by the system.
    Under this method, the stars, planets, and telescopes do not know about each other 
    (e.g., the planet isn't orbiting star).
    """)
    stars, planets, telescopes = star_system.get_system_objects()

    star = stars[0]
    planet = planets[0]

    star.add_orbiting_object(planet)
    eep.visualize.animate_3d_planetary_system(star)

    print("""
    The GenerateSystem is a child of dict, so we can manually edit the parameters, then re-create the star system: 
    """)

    star_system["planet_parameters"]["eccentricity"] = .6
    star_system["planet_parameters"]["inclination"] = (30, "deg")

    stars, planets, telescopes = star_system.get_system_objects()

    star = stars[0]
    planet = planets[0]

    star.add_orbiting_object(planet)
    eep.visualize.animate_3d_planetary_system(star)

    print("""
    If the .exo file is already setup and ready to go, you can get a list of ready-to-run telescopes with 
    initialize_experiments():
    """)

    telescopes = star_system.initialize_experiments()

    telescope = telescopes[0]
    telescope.collect_data()

    lightcurve = telescope._pure_lightcurve.copy()
    time_domain = telescope._time_domain.copy()
    eep.visualize.interactive_lightcurve(time_domain, lightcurve)

    # Remove this line to keep the demo template file around for your perusal
    # TODO: Add a demo template somewhere in the exoechopy examples for use in multiple demos, point to it here
    os.remove(working_folder/demo_template_filename)


if __name__ == "__main__":
    run()


